### ISSUE TITLE
Different ID Format Between Initial Time Table Netex Data and Baseline Netex Data

### ISSUE THREAD

**Issue by sunghangga** [BISONNL/NeTEx-NL#11]
Hi , I want to ask about xml netex data. For example, I have 2 example xml netex from http://data.ndovloket.nl/netex/cxx/. Files consisting of initial (annual) timetabel and baseline. But they have different format ID name, for example: Line ID (initial timetable) = cxx:LN:A001 and Line ID (baseline) = CXX:Line:A001. Do I have to normalize the ID in order to be able to update the initial timetable data? or initial timetable data must be separated with baseline data?

If they must be separated, I have to create in the same or separate table? Thank you, I hope you could help me

**Comment by hennoit** [comment]
In principle every publication contains a 'complete' timetable and thus is independent of previous publications, so IDs _could_ change between publications. But in practice we expect (most) IDs to stay the same, certainly for high level elements such as _Lines_. 
What you see is probably the result of the fact that operators are still busy developing their NeTEx output and are still finetuning things. The LineID in the CXX _baseline_ files has the format that is expected by (the latest versions of) the Dutch NeTEx Profile. In previous versions of the Dutch NeTEx Profile the rules for IDs were less strict, so that then CXX could use a somewhat different format.

Like I wrote above, each publication is 'complete' and therefore completely replaces the previous publication (for the same area). That means that this one time you will probably have to match the new LineIDs with the old LineIDs in order to update your database, but this should not be necessary anymore for future publications.

**Comment by sunghangga** [comment]
> In principle every publication contains a 'complete' timetable and thus is independent of previous publications, so IDs _could_ change between publications. But in practice we expect (most) IDs to stay the same, certainly for high level elements such as _Lines_.
> What you see is probably the result of the fact that operators are still busy developing their NeTEx output and are still finetuning things. The LineID in the CXX _baseline_ files has the format that is expected by (the latest versions of) the Dutch NeTEx Profile. In previous versions of the Dutch NeTEx Profile the rules for IDs were less strict, so that then CXX could use a somewhat different format.
> 
> Like I wrote above, each publication is 'complete' and therefore completely replaces the previous publication (for the same area). That means that this one time you will probably have to match the new LineIDs with the old LineIDs in order to update your database, but this should not be necessary anymore for future publications.

Thanks for your information, it helps a lot.
