### ISSUE TITLE
Multiple Update New Netex Data (annual) to Baseline Netex Data

### ISSUE THREAD

**Issue by sunghangga** [BISONNL/NeTEx-NL#12]
Hi @hennoit , I would to ask about update New Netex Data (annual) to Baseline Netex Data. I have data like this: 

![image](https://user-images.githubusercontent.com/29428699/135823331-2f515ad1-347e-422d-8bd9-3d4861f2525c.png)

Referring to our previous discussion regarding the difference ID between new data netex with baseline data netex in this conversation https://github.com/BISONNL/NeTEx-NL/issues/11, the ID must be update to baseline netex data or newest ID format.

For version "202102" is new netex version data (annual) and "2021001" is baseline netex data. So far, I have updated the data by matching the last data after ":", in this case I use "22010020" to find ID from new netex data (annual) and updated to baseline data. But for this case, I have two "22010020" in my table which source from new netex data (annual). How do I update it? Would you share your idea for my case? Thank you, I hope you could help me

**Comment by hennoit** [comment]
In the Dutch NeTEx Profile we require identifiers to be created as "<codespace>:<type>:<name>", so that they are always unique within The Netherlands. Each producer has its own Codespace; the possible values are fixed on the national level - see https://github.com/BISONNL/export/blob/main/xml/NeTEx_BISON_codespaces.xml 

So in your case you should probably not only match the "<name>" part, but also the "<codespace>" part of the identifier.
The Codespace should be upper case ("CXX"). That the older id's have lower case ("cxx") again is probably because that delivery was still in the development phase (just like "RoutePoint" was still written as "RP").

**Comment by sunghangga** [comment]
Thank you for your explanation, that's very helpful
