### ISSUE TITLE
Error in XSD concerning FromPointRef / ToPointRef

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#2]
Our documentation states:

> Een TimingLink verwijst naar het begin- en eindpunt (FromPointRef en ToPointRef, type
> is ScheduledStopPoint of TimingPoint) en geldt voor een specifieke OperationalContext.

> • Een RouteLink verwijst naar begin- en eindpunt (FromPointRef en ToPointRef, type is
> RoutePoint) en geldt voor een specifieke OperationalContext.

Our XSD implements only the reference check for TimingLink which, only points to ScheduledStopPoint.

https://github.com/BISONNL/NeTEx-NL/blob/master/xsd/netex-nl.xsd#L1657

**Comment by hennoit** [comment]
De huidige constraints op FromPointRef en ToPointRef zijn inderdaad fout. We moeten als werkgroep nog structureel kijken naar welke constraints we verder nog willen verwijderen, dan wel toevoegen.

**Comment by sunghangga** [comment]
> De huidige constraints op FromPointRef en ToPointRef zijn inderdaad fout. We moeten als werkgroep nog structureel kijken naar welke constraints we verder nog willen verwijderen, dan wel toevoegen.

Hi Henno, I want to ask about xml netex data. For example, I have 2 example xml netex from http://data.ndovloket.nl/. Files consisting of new (all operator) and baseline. But they have different format ID name, for example: Line ID (new) = cxx:LN:A001 and Line ID (baseline) = CXX:Line:A001. Do I have to normalize the ID in order to be able to update the new data? or new data must be separated with baseline data?

If they must be separated, I have to create in the same or separate table? Thank you, I hope you could help me

**Comment by skinkie** [comment]
> If they must be separated, I have to create in the same or separate table? Thank you, I hope you could help me @hennoit

Lets start that you should not hijack a discussion to ask a new question. Please open a new issue.

**Comment by sunghangga** [comment]
> > If they must be separated, I have to create in the same or separate table? Thank you, I hope you could help me @hennoit
> 
> Lets start that you should not hijack a discussion to ask a new question. Please open a new issue.

Sorry for that, I've create new issue.

**Comment by hennoit** [comment]
In the newest versions of the Dutch NeTEx Profile (9.2.x) _all_ constraints from the CEN NeTEx standard have been included. This also resolves the problem concerning FromPointRef / ToPointRef described here.
So this issue can be closed.
